<a href="https://colab.research.google.com/github/pradiptars/Data-Cleaning/blob/main/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
path = r"/content/drive/MyDrive/Boston.csv"
df = pd.read_csv(path)
df.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [4]:
X = df.drop('zn', axis=1)
y = df['zn']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
print("shape of X_train : ", X_train.shape)
print("shape of X_test : ", X_test.shape)
print("shape of y_train : ", y_train.shape)
print("shape of y_test : ", y_test.shape)

shape of X_train :  (404, 14)
shape of X_test :  (102, 14)
shape of y_train :  (404,)
shape of y_test :  (102,)


In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [8]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [9]:
lr.coef_

array([ 2.170166  ,  1.86702054, -3.62112122,  0.40409929, -1.59155087,
        1.2327327 , -1.69421638, 13.88556441, -7.66072603, 12.13720613,
       -6.12694147, -0.21731591,  2.89291568,  2.97510459])

In [10]:
lr.intercept_

11.569306930693072

In [11]:
X_test[0, :]

array([-0.54466836, -0.39680933, -1.00711147, -0.27808871, -0.39541229,
        0.14128239,  0.55591643, -0.54585271, -0.50779731, -0.65092617,
       -0.77195078,  0.42887165, -0.48121032,  0.08620327])

In [12]:
lr.predict([X_test[0, :]])

array([4.95362928])

In [13]:
lr.predict(X_test)

array([ 4.95362928e+00,  1.63297392e+01,  1.14002319e+01,  1.51272226e+01,
       -1.19235881e+00,  1.11360450e+01,  1.01184501e+01, -1.25219692e+01,
        5.34465600e+00,  3.49501678e+00,  3.71415970e+00,  3.19367190e+01,
        4.66959847e+00,  1.91139842e+01,  9.22644392e+00,  6.21659907e+00,
       -2.40464281e+01, -4.50432217e+00,  4.35385811e+01, -1.98505262e+00,
        1.14400081e+01,  1.52451320e+01,  6.96101827e-01, -5.25840251e+00,
       -6.35586942e+00, -1.17783613e-01,  1.45815588e+01,  2.31744290e+00,
        7.44737012e+00,  6.56310227e+00,  5.02458575e+00,  1.03881750e+01,
       -6.14449856e+00, -8.62841834e+00,  3.82523964e+00, -1.96777568e+00,
        1.61028341e+01,  8.78623686e+00,  1.17783136e+01,  1.66214846e+01,
        8.41094410e+00,  2.27456839e+00,  3.62917319e+01,  2.80401537e+01,
        5.36924280e+00, -6.18759984e+00, -3.83751120e+00,  1.67338518e+01,
        6.09835616e+00,  1.92907121e+01,  2.81786059e+01,  2.94207740e+01,
       -1.05332994e+00, -

In [14]:
y_test

173     0.0
274    40.0
491     0.0
72      0.0
452     0.0
       ... 
412     0.0
436     0.0
411     0.0
86      0.0
75      0.0
Name: zn, Length: 102, dtype: float64

In [15]:
lr.score(X_test, y_test)

0.46511231184992174

In [16]:
from sklearn.linear_model import Ridge, Lasso


In [17]:
rd = Ridge()
rd.fit(X_train, y_train)
rd.score(X_test, y_test)

0.46665295987075506

In [18]:
ls = Lasso()
ls.fit(X_train, y_train)
ls.score(X_test, y_test)

0.45364970352849365

In [19]:
rd2 = Ridge(alpha=2)
rd2.fit(X_train, y_train)
rd2.score(X_test, y_test)

0.46802786111824346

In [20]:
ls2 = Lasso(alpha=2)
ls2.fit(X_train, y_train)
ls2.score(X_test, y_test)

0.42138581504110406

In [21]:
ls3 = Lasso(alpha=3)
ls3.fit(X_train, y_train)
ls3.score(X_test, y_test)

0.3951799160773284

In [22]:
lr.predict(X_test)

array([ 4.95362928e+00,  1.63297392e+01,  1.14002319e+01,  1.51272226e+01,
       -1.19235881e+00,  1.11360450e+01,  1.01184501e+01, -1.25219692e+01,
        5.34465600e+00,  3.49501678e+00,  3.71415970e+00,  3.19367190e+01,
        4.66959847e+00,  1.91139842e+01,  9.22644392e+00,  6.21659907e+00,
       -2.40464281e+01, -4.50432217e+00,  4.35385811e+01, -1.98505262e+00,
        1.14400081e+01,  1.52451320e+01,  6.96101827e-01, -5.25840251e+00,
       -6.35586942e+00, -1.17783613e-01,  1.45815588e+01,  2.31744290e+00,
        7.44737012e+00,  6.56310227e+00,  5.02458575e+00,  1.03881750e+01,
       -6.14449856e+00, -8.62841834e+00,  3.82523964e+00, -1.96777568e+00,
        1.61028341e+01,  8.78623686e+00,  1.17783136e+01,  1.66214846e+01,
        8.41094410e+00,  2.27456839e+00,  3.62917319e+01,  2.80401537e+01,
        5.36924280e+00, -6.18759984e+00, -3.83751120e+00,  1.67338518e+01,
        6.09835616e+00,  1.92907121e+01,  2.81786059e+01,  2.94207740e+01,
       -1.05332994e+00, -

In [23]:
y_test

173     0.0
274    40.0
491     0.0
72      0.0
452     0.0
       ... 
412     0.0
436     0.0
411     0.0
86      0.0
75      0.0
Name: zn, Length: 102, dtype: float64

In [24]:
from sklearn.metrics import mean_squared_error
import numpy as np
mse = mean_squared_error(y_test, lr.predict(X_test))
rmse = np.sqrt(mse)

print("means squre error : ", mse)
print("root means squre error : ", rmse)

means squre error :  307.19467760541255
root means squre error :  17.526970006404774
